package com.lpf.greendb.db.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PERSON".
 */
public class Person {

    private Long id;
    /** Not-null value. */
    private String personId;
    private String personName;

    public Person() {
    }

    public Person(Long id) {
        this.id = id;
    }

    public Person(Long id, String personId, String personName) {
        this.id = id;
        this.personId = personId;
        this.personName = personName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getPersonId() {
        return personId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPersonId(String personId) {
        this.personId = personId;
    }

    public String getPersonName() {
        return personName;
    }

    public void setPersonName(String personName) {
        this.personName = personName;
    }

}
